spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xuanke?charset=utf8
    username: root
    password: yhh666888.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initial-size: 100
      min-idle: 100
      max-active: 1000
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall,slf4j
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      use-global-data-source-stat: true

  jpa:
    show-sql: true

  redis:
    host: localhost
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: 3000
        max-idle: 8
        min-idle: 0
    timeout: 1000

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML

logging:
  file:
    name: run.log
    max-size: 1MB
    max-history: 7